### ISSUE TITLE
Feature Request: Offline Validation

### ISSUE THREAD

**Issue by nikstur** [python-jsonschema/check-jsonschema#167]
I'm looking to use jsonschema in Nix (as in NixOS) tests to validate whether an application generates valid JSON documents. All Nix tests, however, run in a sandbox that has no network access to enable reproducible builds.

I already mentioned this in the jsonschema repository https://github.com/python-jsonschema/jsonschema/issues/1007

The probably easiest option would be to introduce a `--base-uri` command line flag like the legacy jsonschmea CLI does to override the `$id` field of the schema with a local path.

What is your opinion on that?

**Comment by sirosen** [comment]
I'd be open to adding features and making changes to support this use case!
Before I get started, however, I want to make sure I understand your needs correctly.

In the original issue, you asked about disabling remote resolution. Here, you're suggesting replacing the base path for a schema to point at local files. Both of these features could be useful, but they would do different things.

If you have a family of related schemas which you download and use with a customized base path, this will work if the main schema is the only one with external references. However, if you have three schemas which reference one another in order (schema1 references schema2, schema2 references schema3), the behavior becomes more complicated. I'll need to tinker with this and look at the possible behaviors to form an opinion about how to handle these cases -- but if you have thoughts about this as the requester, I'd be very interested!

Disabling external network access is something in which I'm not sure we can give you the behavior you want (partial validation). I'm pretty sure that the only safe behavior if we disable network calls is to error out if one is requested. I could be convinced otherwise, but it would require some investigation/proof of concept to demonstrate that it works okay. That doesn't mean that feature would be useless: better to error quickly and clearly than slowly and in an unclear manner. If it were implemented as such, would you still be interested in the feature?

**Comment by nikstur** [comment]
Thanks for taking the time to reply! 
Yes, you're right, I was a bit unclear. Let me make it clearer:

I think the original request came from a misunderstanding of mine. I thought jsonschema validated external references in the JSON document instance (NOT the schema), i.e. to check if they are working links. I understand now that this was a wrong assumption and the validation failed because jsonschema couldn't resolve a reference to another schema. I agree, partial validation in the sense of not retrieving references to other schemas, does not make much sense. Erroring out early does seem desirable regardless.

What I think I really need is to provide a custom base path to a schema. I'll give you the specific example I was working with: I looked at validating a CycloneDX Software Bill of Materials with [this schema](https://github.com/CycloneDX/specification/blob/master/schema/bom-1.3.schema.json) which references `spdx.schema.json` in the same directory. If I could validate this by pulling all the required files into a local directory and pointing check-jsonschema at it, my use case would be fulfilled. 

It would probably make sense to provide the same base path to all referenced schemas so that they can simply be put into a flat directory and can all be found (this still might not fulfill all edge cases). For a first implementation, however, I think just changing the base path of the "root" schema is good enough.

**Comment by jalapenopuzzle** [comment]
I have this issue of needing to validate schemas off-line.
I had planned to use check-jsonschema as a validation tool, but it is unsuitable for my task without the feature of offline validation.
I was able to use @pspot2 's technique to construct a working referenced schema set, but I had to hard-code an absolute filesystem path into the top level schema which is unsuitable for deployment. I require a `--base-uri` option.

**Comment by sirosen** [comment]
I've finally made some more time in my schedule for `check-jsonschema` work, and I plan to address this quite soon, now that `check-jsonschema` is converted from `RefResolver` to the new `referencing` implementation. My apologies for the wait and thanks to everyone for their patience -- I'm aware that this is a needed feature for a number of usages.

The plan is to do this by forcibly setting the `$id` attribute inside of `check-jsonschema` if a `--base-uri` is given. That is, if you have a schema `foo.json` and you call `check-jsonschema --schemafile https://example.org/foo.json --base-uri file:///home/user/foo.json`, `check-jsonschema` will download and parse the schema from `example.org`, but then rewrite the `$id` field before running validation.

The rationale for doing it this way is a mix of things, but primarily breaks down into these two points:

1. `referencing` does not provide an option (that I can see) to provide an explicit base URI.

I'm undecided about whether or not to file an issue to ask for this issue. It doesn't seem like critical functionality, and I think the implementation would be the same inside of `referencing` as what we'll do as callers of it. Possibly slower because it will need to make at least a shallow copy of the top level of the schema doc before modifying it.
Anyway, the solution needs to work against the current API if possible, so whether or not `referencing` changes, `check-jsonschema` can run ahead and implement something.

2. The spec prefers `$id` to the retrieval URI when both are available.

`check-jsonschema` now has code which implements that behavior. So if the `$id` is not set and there is a retrieval URI, I see more risk that behavior will accidentally diverge.

**Comment by sirosen** [comment]
I know this has been a long time coming, but `check-jsonschema` v0.25.0 has just been released with support for `--base-uri`!

I think there's some mild risk that the title of this issue could be confusing if I close it as-is, but the needs of everyone in this thread should be met by `--base-uri`. It's not a true "offline mode" but it's pretty close.
So I'm going to resolve but I'm also going to update the issue title.

If anyone is seeing issues with v0.25.0 or later, please open a follow up issue.
