### ISSUE TITLE
Include Buildkite pipeline schema

### ISSUE THREAD

**Issue by mwgamble** [python-jsonschema/check-jsonschema#198]
As a user of Buildkite, I would super appreciate it if their pipeline schema was bundled with check-jsonschema :pray: 

https://github.com/buildkite/pipeline-schema/

**Comment by sirosen** [comment]
Right now, the only schemas included are listed in schemastore. I'm not strictly against adding something else, but it makes things easier for me if I can point at them as my "source of truth".

I therefore come to you with a request back, so that I can fulfill this, that you get Buildkite added to schemastore.

Schemastore is pretty easygoing about new schemas. They'll generally ask that you do the work of adding one, but it's not very hard. Since this one is hosted on GitHub, you'll basically just need to add a link and description to their catalog. Here's an example block which defines a github-hosted schema for angular:
https://github.com/SchemaStore/schemastore/blob/be5a3214685981a4574819ec0a59f8dbc66980fc/src/api/json/catalog.json#L77-L82

To explain a little bit why it helps:
- schemastore provides me with a canonical link to the schema
- their catalog lists matching filename patterns, which I use as a basis for check-jsonschema's pre-commit hooks
- it will be very useful when I finish my project to pull the vendored schemastore schemas into a separate library

If you don't feel comfortable or able to add the schema to schemastore, I'll try to get to it, but I'm pretty swamped with work right now, so no promises on timeline.

**Comment by mwgamble** [comment]
It is in schemastore:

https://github.com/SchemaStore/schemastore/blob/be5a3214685981a4574819ec0a59f8dbc66980fc/src/api/json/catalog.json#L524-L542

For reasons I don't understand, it's just not hosted on the schemastore website.

**Comment by sirosen** [comment]
🤦 Sorry about that! I had searched, but missed it! Maybe I looked for `buildkite` (all lowercase).

I'll work on pulling this in when I'm next able.

**Comment by sirosen** [comment]
I've just released v0.20.0 which includes this. 🥳 

Please let me know if you run into any issues using it, and thanks for putting in the request!
