### ISSUE TITLE
--schemafile from $schema

### ISSUE THREAD

**Issue by 6nv** [python-jsonschema/check-jsonschema#416]
Hi, can check-jsonschema automatically detect which schema to validate against based on the value in `$schema`? I found [--check-metaschema](https://check-jsonschema.readthedocs.io/en/stable/usage.html#id3) which is almost exactly what I want, but not quite. I want to write a pipeline to automatically validate all json files against their respective schemas without having to write a new check each time I add a new file.

---

a.json:
```json
{
 "$schema": "../schema/a.json"
}
```

b.json:
```json
{
 "$schema": "../schema/b.json"
}
```

(...you could imagine I have several more json files, each with their own schema.)

../schema/a.json
```json
{
 "$schema": "http://json-schema.org/draft-04/schema#",
 ...
}
```

../schema/b.json
```json
{
 "$schema": "http://json-schema.org/draft-04/schema#",
 ...
}
```

---

I **want** to write something like this:

```shell
$ check-jsonschema database/*.json
# Usage: check-jsonschema [OPTIONS] INSTANCEFILES...
# Error: Either --schemafile, --builtin-schema, or --check-metaschema must be provided
```

But currently I need to write this:

```shell
$ check-jsonschema --schemafile schema/a.json database/a.json
$ check-jsonschema --schemafile schema/b.json database/a.json
$ check-jsonschema --schemafile schema/c.json database/c.json
...
```

I tried `--builtin-schema` which looked promising but still not quite what I'm looking for. Do I have any options right now or is this not currently a feature of this tool? Thanks!

Might be a duplicate of #310

**Comment by sirosen** [comment]
I think this is the same feature as requested in #310.

Current status is that I haven't been working on it. I've been stretched a bit thin since midwinter this past year and unable to make much progress on most FOSS projects. I'm going to close to consolidate with #310, but feel free to either add detail there if you think there's important information missing from that conversation, or to reopen this if you think I'm wrong and it's not a duplicate.

**Comment by thiagowfx** [comment]
You may find https://github.com/python-jsonschema/check-jsonschema/issues/310#issuecomment-3062174357 useful.
