### ISSUE TITLE
`src/check_jsonschema/builtin_schemas/vendor` file organization

### ISSUE THREAD

**Issue by jrdnbradford** [python-jsonschema/check-jsonschema#425]
I noticed that the `sha256` hashes, licenses, and schemas for vendor schemas are all in `src/check_jsonschema/builtin_schemas/vendor`. Any interest in creating subdirectories there for general organization? In other words:

- `src/check_jsonschema/builtin_schemas/vendor/licenses`
- `src/check_jsonschema/builtin_schemas/vendor/sha256`
- leaving the schemas under `vendor`

From a quick look it seems like only a small change to `vendor-schemas.py` would be required for auto-updating the schemas.

I'd be happy to take this on and put in a PR if you're interested. I have some extra time on my hands and get a lot of use out of this repo. 🦖

**Comment by sirosen** [comment]
Yeah, I think that would be a nice little change, and would make it easier to browse that directory.
I haven't thought very much about it since setting that dir up.

Thanks so much for the suggestion and the willingness to work on it! I'm eager for a PR. :heart:
(And no worries if you do it and we uncover some surprisingly trickiness -- I'm happy to start from a partial PR and help work out whatever might be a sticking point.)

**Comment by jrdnbradford** [comment]
Awesome, thanks as always!
