### ISSUE TITLE
Unable to control terminal colors

### ISSUE THREAD

**Issue by ssbarnea** [python-jsonschema/check-jsonschema#87]
I tried to look for various common methods to control the use of ANSI colors in output but found none as working or documented.

As I am trying to use this tool from code, I have no need for ANSI escapes.

None helped: PY_COLORS=0, NO_COLOR=1, TERM=dumb.

**Comment by sirosen** [comment]
👍 This is a good idea/request. I'll implement `NO_COLOR=1` and document it.

Up through the last release, the ANSI escapes were used directly in a `print`, so there's no way to control it. In `main`, it's slightly better since `click` will automatically strip ANSI escapes if the output terminal is not a tty, but there's still no control.

If you absolutely need this right now and can't wait for a release, you could pipe to `strip-ansi`.

**Comment by ssbarnea** [comment]
That was quick! Thanks! I was expecting to do it myself after getting an ack about which path to take.

Yep, the taken one is ideal as least intrusive and most terminals do support ansi anyway.

**Comment by ssbarnea** [comment]
@sirosen I would personally do my best to avoid using strip-ansi npm package because I observed                                          that its two maintainers are far from friendly. Multiple people asked for typescript support and they basically locked the tickets. Changes they made to latest release prevented use with typescript and they have no plans to fix it. See https://github.com/chalk/strip-ansi/issues/11#issuecomment-305543029 and https://github.com/chalk/strip-ansi/issues/42#issuecomment-968177433

I tried to find a typescript alternative but failed so I will likely wait for a new release of check-jsonschema.

BTW, if you are curious, I am working on recording the validations errors received from various validators on my schemas, so I can spot when a slight change in schema cam make the validators go wild. This can also be used to compare output from various validators, which varies a LOT. See https://github.com/ansible/schemas/pull/249/files

As a schema author, I need to do my best to help validators provide best possible errors for the users.
