### ISSUE TITLE
Improper use of stdout and stderr

### ISSUE THREAD

**Issue by ssbarnea** [python-jsonschema/check-jsonschema#88]
It seems that `check-jsonschema` implementation does not follow the basic cli guidelines (see https://clig.dev/#the-basics section on stdout and stderr).

* found validation errors are expected program output, so they should go to stdout
* no validation errors is a success, so not stdout output is expected
* `Schema validation errors were encountered.` and `ok -- validation done` counts as messaging/logging, and they should go to `stderr` instead of `stdout`, something that tools usually even control with verbosity/quite flags.

Following these recommendation is essential as other tools would rely on processing output and either ignore or silence stderr, which is never to be processed.

Based on my tests it seems that the current behavior got the stdout and stderr usage swapped.

When I tried to `2>/dev/null` i realised that there was nothing useful on `stdout`.

That is a relatively common mistake to do when someone implements a linter as "stderr" name gives the impression that it for errors, but when the goal of the tool is to identify problems/errors in received data, that is not really the "stderr" kind of error.

You can think it from another angle: it desired/normal/expected outcome to find errors in schema instances, so no need to send them to stderr.

I hope that explains it. I an easily make a PR to fix if you want.

**Comment by sirosen** [comment]
The tool's primary output has always been its exit code. Everything else has been treated as "informational logging". As a result, I've been rather casual about which stream is used for which bit of output. That might sound a bit like an excuse, but I'm just trying to provide some context for why it is this way today.

I'd like to address this, and will look through the existing output, but I'd like to make two notes:
- You're parsing output from a tool which has not been carefully designed to produce parseable output. It may happen to be the case that the content of stderr is nicely structured and can be parsed, but if so that's a happy accident. The typical caveats about "output may change between versions" therefore apply.
- When I have some more time to tinker, I've wanted to redo the output in significant ways, including the addition of output formatting options. This has implications about the future parseability of output.

Combining pragmatism with some amount of foresight about the future of this tool...
1. I'll make changes in the coming days-to-weeks to make stdout more readily parseable and will not intentionally sabotage parsing code by changing the output format. However, `check-jsonschema` will not be adding any new documentation or guarantee that the output will not change between versions.
2. When/if an output formatter is added, the goal will be to provide machine parseable output in at least one format (e.g. JSON).

**Comment by sirosen** [comment]
I've added support for JSON output (`-o JSON`), along with various changes to the text formatted output. I'm going to mark this closed.

I'd recommend using the JSON output if you need to use this as part of a complex pipeline. The format isn't documented yet, but I plan to add doc and perhaps even a schema for it in the future.

**Comment by ssbarnea** [comment]
Thanks. I am current saving and tracking the output during schema testing from both schemastore and ajv and using JSON would like it more stable between updates. The whole point for me is to evaluate how a schema change affects the consumers (validators).

ajv output was already `json`.
